//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Behaviors/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""OnFoot"",
            ""id"": ""a581c9a7-0b04-4b18-8e00-cf11d5600eff"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""68f3c82c-f3b8-4191-8bf2-75476f108e26"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""7701bd05-e474-4f2f-a1fc-965dc8968939"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""8d854f63-cf29-490d-9588-edd8a5c5db5a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""1ce2f36e-e764-4abf-8d88-3a903f878132"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""277df051-305c-4f5a-ac4c-9c05083b3b12"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""a6de7bca-b0b9-45c9-91b1-2a6355b990c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchTools"",
                    ""type"": ""Button"",
                    ""id"": ""4f3a58ae-093c-4ebf-b538-e18e4eee1895"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SwitchActionMaps"",
                    ""type"": ""Button"",
                    ""id"": ""9ca14e5d-b3f5-400b-a16d-c5c6e15afb1a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OperateTool"",
                    ""type"": ""Button"",
                    ""id"": ""6ec9fe64-0ba3-422c-864a-88cac1dbf882"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""30fba54c-8382-49a9-96b0-beef7f17cc8e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Astrolabe"",
                    ""type"": ""Button"",
                    ""id"": ""df80b850-b7af-4397-97f7-8826225052de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Flashlight"",
                    ""type"": ""Button"",
                    ""id"": ""eab52f54-1ad2-499d-b564-959a3e8e2ecd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Flaregun"",
                    ""type"": ""Button"",
                    ""id"": ""204b625f-cd6f-4dbe-a080-a71675eb425d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LightningBottle"",
                    ""type"": ""Button"",
                    ""id"": ""c2055052-548f-41f3-8790-dc49cbc8b4e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EastButton"",
                    ""type"": ""Button"",
                    ""id"": ""2aed8480-fffe-4342-87f6-64b29ff53c85"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SouthButton"",
                    ""type"": ""Button"",
                    ""id"": ""b213247c-9f00-4761-8907-b89789f476bf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""235f3f78-212c-4bd9-b2f6-193c431bf03c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a8724b82-13ba-46b3-9e8b-082adb53cd59"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""OnFoot;Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""97cb3a51-5cb2-4a47-8c79-dc78e005cbce"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""OnFoot;Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""11f81ccc-f019-42cb-b90f-0f0a467bd4f3"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""OnFoot;Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""80b992b6-fa14-422d-9281-9982e5c971b3"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""OnFoot;Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftStick"",
                    ""id"": ""b9684086-8bd8-42e3-afc2-ed7c6aa79358"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2,StickDeadzone(min=0.35)"",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""53937799-30a8-4492-8825-63f3c71fa21a"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""eba69174-0062-414e-8be5-316498754cb2"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ac5e6f1d-024d-464a-86b9-51e5954e1d6a"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9e249f89-1780-40ee-91fa-dba10d9d0a7f"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ed4ab02f-49c9-424c-af81-b1f351d48551"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4bc505ff-af2d-48d7-807f-fe69cde0ae55"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""RightStick"",
                    ""id"": ""11035361-6972-40a8-84fe-84767a367a75"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone(min=0.35)"",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""03e48f8e-3ae5-43db-ab43-6af091862d80"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=10)"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""94de6595-cb32-431e-b49a-ca7587954e31"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=10)"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3cc3ad47-72b4-4df7-979d-6412972bac4a"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=10)"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6da0c500-75c0-45af-a6be-b0f17bf24797"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=10)"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""067caa13-c1d4-4afd-9e2a-334870e8c200"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0cd67736-095b-4f51-a23a-b59afe4af068"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f8ecab8-9fe8-4907-afbe-62985abb0e0a"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a52f071-ef26-4d60-be0c-0b8da6e9fe22"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3bd1a45-6022-4ab7-9829-43488a1b3a1e"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbba2f37-c124-4794-9845-b5f43fc69fe7"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""afcf14e9-3e44-406f-ae38-c23b95dc2d84"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SwitchTools"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f0c5f51-f868-4c76-885f-60b42844f2fe"",
                    ""path"": ""<Keyboard>/f4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard;Gamepad"",
                    ""action"": ""SwitchActionMaps"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42a1a304-a146-40e4-8b72-c786820b1dab"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""OperateTool"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""158289ef-86e4-4158-bab6-9bcbf2400e5d"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e53bbbe-c06d-48fb-bf72-05c0e15fc254"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Astrolabe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""53645400-82fe-4e30-99b2-30ab263b6932"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Flashlight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7d492db-f87e-404f-82d6-1a9b1273cce7"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Flaregun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41fc7ff4-cc96-4b4e-8bdb-5e2557fbb7ca"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LightningBottle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f023f691-e271-4e1f-a401-81d01662da3f"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""EastButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e711f0d0-2d11-4c29-80aa-02b32291f547"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SouthButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Sailing"",
            ""id"": ""fc12cbad-72ed-48d9-80f0-80a5978c28b8"",
            ""actions"": [
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""2ba5b84b-7f42-45ce-9ed2-3f2372b64bd4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone(min=0.35)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BoatYaw (Direction)"",
                    ""type"": ""Button"",
                    ""id"": ""2c79315d-c8be-4937-8789-3da95f41a48e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToPlayerControls"",
                    ""type"": ""Button"",
                    ""id"": ""52eb7224-f220-4554-8862-1ee0ad08a33d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IncreaseSail"",
                    ""type"": ""Button"",
                    ""id"": ""5f5041c5-fc30-43f2-993d-21874e67f329"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DecreaseSail"",
                    ""type"": ""Button"",
                    ""id"": ""3637af3a-92ce-4948-a396-659dae1c2b3d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BoomRotateRight"",
                    ""type"": ""Button"",
                    ""id"": ""6e414bbd-c835-4845-8eb8-125da7215254"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BoomRotateLeft"",
                    ""type"": ""Button"",
                    ""id"": ""62376119-447f-45af-8bbb-96ab60bf292b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FireAreaFlare"",
                    ""type"": ""Button"",
                    ""id"": ""ecfc8408-d9b0-43b4-a6b3-9079e242d5c2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseMenu"",
                    ""type"": ""Button"",
                    ""id"": ""b4b6a96f-b142-46b6-80e6-a0ede3461162"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JournalMenu"",
                    ""type"": ""Button"",
                    ""id"": ""37c29842-e4e9-427c-844b-8658157b6684"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThirdToFirst"",
                    ""type"": ""Button"",
                    ""id"": ""b7c2cf6d-99c8-4727-876c-35cfcc9c1f0b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EastButton"",
                    ""type"": ""Button"",
                    ""id"": ""23687c06-43e5-4601-acec-2440c1dce4c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SouthButton"",
                    ""type"": ""Button"",
                    ""id"": ""0321b0e4-6869-4789-baad-e407f2016306"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""LeftStick"",
                    ""id"": ""9c39a324-33e2-4011-b120-25e8e6c0f92b"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2,AxisDeadzone(min=0.35)"",
                    ""groups"": """",
                    ""action"": ""BoatYaw (Direction)"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""54824541-d805-47a6-a6c2-425578176a47"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""BoatYaw (Direction)"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""de9e300a-60b0-4231-99cf-462bc30c0338"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""BoatYaw (Direction)"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5374cd4f-e520-4a6b-ab00-9c5d06f4a0c8"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""BoatYaw (Direction)"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a141c82b-6ece-4fcd-a62b-86030266fb37"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""BoatYaw (Direction)"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a89c8549-9402-41c9-8843-ce92e44447da"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ToPlayerControls"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f761711-bd9a-4700-8aa7-18f8e5dc2e68"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""IncreaseSail"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""623a6c9f-d042-494e-826b-0b138cd49e79"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""BoomRotateRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0a90330-63dc-4d33-83d6-7bede6fac515"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""FireAreaFlare"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70dff04a-4fa6-47b2-9390-4f270e69a3de"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""PauseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51689b25-77b7-4ec4-a6e4-51b3b9343cce"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""JournalMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c435a26-d2b4-4297-93f3-66a5499d521e"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""BoomRotateLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f17e55f-7f64-4cdc-88ba-bae221747648"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DecreaseSail"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b9cfad0-3358-47b5-bf14-c9dfd44075e9"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cacde54c-363a-4457-a509-6cb139cf0739"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=50,y=50),StickDeadzone"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1942bd88-1e35-412c-b7e4-d7c4e737ece6"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ThirdToFirst"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91502330-f617-4091-92ea-d65f467b9548"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""EastButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1048b48-c873-431c-a801-21b606b35e9c"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SouthButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""1c59b453-9365-4ccf-9ee9-089176030017"",
            ""actions"": [
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""972c41f4-3dba-4d7a-9377-fadde1998d3b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""de09271b-c8c4-49ec-be14-881e9fe95af2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""e20f28d6-e2b4-4fa7-b43d-f34acad08012"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e6b35c3c-54ca-46e5-8956-5f8a03fb531c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""PassThrough"",
                    ""id"": ""66320ed7-a9bd-4fd7-8006-ab426b4334fe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0a7359fe-5509-4706-8969-3bed8d741200"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiddleClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""490b5941-eb93-4067-8a0b-e44cfa0777ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b7555f9e-959f-4038-ae76-313214ed146a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackedDevicePosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0b970a1c-e10d-4043-bc4f-f97f28b5b0ab"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackedDeviceOrientation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""be290a8c-e42a-4046-a3ea-f145a93aec94"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkipDialog"",
                    ""type"": ""Button"",
                    ""id"": ""123ccabb-3862-4dbe-a66a-ad0e72f92cb2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""d973f826-27a3-494d-8482-1f1ffe88a748"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""bc0cb241-895d-42ed-86f9-01561c0f1571"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""86b8de13-90ef-46e5-b944-a238bd0454a0"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e28da589-da4c-4336-8741-b42c8a982a78"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""65228935-14da-49e5-9100-6fc0757e0956"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e0a2a8f0-4431-462d-b629-58cf8f5a39e8"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""834c39a5-3c38-4163-9843-6dc173d79318"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""920e3315-0c71-42f9-b401-2ec3d1aac624"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d60eb681-e10e-4a82-bc6b-44f6417528f6"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e1a82479-a5fc-4364-be01-e0137c2fda7e"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""36661344-758d-4c96-af65-b45c31ffadd4"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""62df8076-5266-403e-bd25-d044d3f5d03a"",
                    ""path"": ""<Joystick>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5b165206-cb7f-460a-9eb8-f3e4c5d817e6"",
                    ""path"": ""<Joystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3fbcd7a6-82c9-4d28-b592-73e84700f335"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""07c8a4ae-42fa-43b9-8ee4-e7f79c60fab5"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""1c5dd720-a033-4872-95e4-a9de9b0e2402"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b6d5e912-3562-4464-a1ba-36dd6c302f95"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ddefb471-a04a-4f60-a174-2c5e137bb2cb"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""213bacd5-3b8c-441d-9109-932216d2d82e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2d6a6f6a-317c-4ce4-9091-f90bd8a31946"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b9d39d0d-5be2-4a16-8ae0-13237e4697ea"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c7d07c7a-cebf-43cd-b8e8-8b39427a37c3"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""53d79f16-d8db-4720-9de2-58ccecc4250b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d3bf5f8a-482e-48b1-b175-5fdbd6e2a71d"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0e345c10-f886-468c-a5df-0c8de4c0693c"",
                    ""path"": ""*/{Submit}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Gamepad;Touch;Joystick;XR"",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d80612a-a247-495c-9370-5645bc8e8464"",
                    ""path"": ""*/{Cancel}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Gamepad;Touch;Joystick;XR"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df7d322c-43df-4c12-a74f-efe65067eaec"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f549a46b-89ce-4607-b9ed-68678ddcdf7d"",
                    ""path"": ""<Pen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff0a688b-5e1c-4eb9-80c5-bfccb1d4019e"",
                    ""path"": ""<Touchscreen>/touch*/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a214e0a2-4e84-44ab-929b-7015cf9faaf1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c07ec262-ab1d-4983-b668-a56f8d1a5ad7"",
                    ""path"": ""<Pen>/tip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fcc95e55-8ae1-4d28-95df-65def4ac7962"",
                    ""path"": ""<Touchscreen>/touch*/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a4f56e3-8fa2-4fff-ac81-0e1efb784956"",
                    ""path"": ""<XRController>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e858941-9789-46c7-ada2-7b38ff335276"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1cc89a9b-23c5-4bd1-9c51-8a883b5a0bd7"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""MiddleClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c3f9ad0-ff6e-4cfb-9f05-18841db71c49"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7171132-420f-407d-a8d2-59b077a60ce8"",
                    ""path"": ""<XRController>/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""TrackedDevicePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""becd48fd-35fe-4472-a3ad-2983666c1c56"",
                    ""path"": ""<XRController>/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""TrackedDeviceOrientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73184a13-394e-4960-9b58-78586d438681"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkipDialog"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // OnFoot
        m_OnFoot = asset.FindActionMap("OnFoot", throwIfNotFound: true);
        m_OnFoot_Movement = m_OnFoot.FindAction("Movement", throwIfNotFound: true);
        m_OnFoot_Jump = m_OnFoot.FindAction("Jump", throwIfNotFound: true);
        m_OnFoot_Look = m_OnFoot.FindAction("Look", throwIfNotFound: true);
        m_OnFoot_Crouch = m_OnFoot.FindAction("Crouch", throwIfNotFound: true);
        m_OnFoot_Sprint = m_OnFoot.FindAction("Sprint", throwIfNotFound: true);
        m_OnFoot_Interact = m_OnFoot.FindAction("Interact", throwIfNotFound: true);
        m_OnFoot_SwitchTools = m_OnFoot.FindAction("SwitchTools", throwIfNotFound: true);
        m_OnFoot_SwitchActionMaps = m_OnFoot.FindAction("SwitchActionMaps", throwIfNotFound: true);
        m_OnFoot_OperateTool = m_OnFoot.FindAction("OperateTool", throwIfNotFound: true);
        m_OnFoot_Reload = m_OnFoot.FindAction("Reload", throwIfNotFound: true);
        m_OnFoot_Astrolabe = m_OnFoot.FindAction("Astrolabe", throwIfNotFound: true);
        m_OnFoot_Flashlight = m_OnFoot.FindAction("Flashlight", throwIfNotFound: true);
        m_OnFoot_Flaregun = m_OnFoot.FindAction("Flaregun", throwIfNotFound: true);
        m_OnFoot_LightningBottle = m_OnFoot.FindAction("LightningBottle", throwIfNotFound: true);
        m_OnFoot_EastButton = m_OnFoot.FindAction("EastButton", throwIfNotFound: true);
        m_OnFoot_SouthButton = m_OnFoot.FindAction("SouthButton", throwIfNotFound: true);
        // Sailing
        m_Sailing = asset.FindActionMap("Sailing", throwIfNotFound: true);
        m_Sailing_Look = m_Sailing.FindAction("Look", throwIfNotFound: true);
        m_Sailing_BoatYawDirection = m_Sailing.FindAction("BoatYaw (Direction)", throwIfNotFound: true);
        m_Sailing_ToPlayerControls = m_Sailing.FindAction("ToPlayerControls", throwIfNotFound: true);
        m_Sailing_IncreaseSail = m_Sailing.FindAction("IncreaseSail", throwIfNotFound: true);
        m_Sailing_DecreaseSail = m_Sailing.FindAction("DecreaseSail", throwIfNotFound: true);
        m_Sailing_BoomRotateRight = m_Sailing.FindAction("BoomRotateRight", throwIfNotFound: true);
        m_Sailing_BoomRotateLeft = m_Sailing.FindAction("BoomRotateLeft", throwIfNotFound: true);
        m_Sailing_FireAreaFlare = m_Sailing.FindAction("FireAreaFlare", throwIfNotFound: true);
        m_Sailing_PauseMenu = m_Sailing.FindAction("PauseMenu", throwIfNotFound: true);
        m_Sailing_JournalMenu = m_Sailing.FindAction("JournalMenu", throwIfNotFound: true);
        m_Sailing_ThirdToFirst = m_Sailing.FindAction("ThirdToFirst", throwIfNotFound: true);
        m_Sailing_EastButton = m_Sailing.FindAction("EastButton", throwIfNotFound: true);
        m_Sailing_SouthButton = m_Sailing.FindAction("SouthButton", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Navigate = m_UI.FindAction("Navigate", throwIfNotFound: true);
        m_UI_Submit = m_UI.FindAction("Submit", throwIfNotFound: true);
        m_UI_Cancel = m_UI.FindAction("Cancel", throwIfNotFound: true);
        m_UI_Point = m_UI.FindAction("Point", throwIfNotFound: true);
        m_UI_Click = m_UI.FindAction("Click", throwIfNotFound: true);
        m_UI_ScrollWheel = m_UI.FindAction("ScrollWheel", throwIfNotFound: true);
        m_UI_MiddleClick = m_UI.FindAction("MiddleClick", throwIfNotFound: true);
        m_UI_RightClick = m_UI.FindAction("RightClick", throwIfNotFound: true);
        m_UI_TrackedDevicePosition = m_UI.FindAction("TrackedDevicePosition", throwIfNotFound: true);
        m_UI_TrackedDeviceOrientation = m_UI.FindAction("TrackedDeviceOrientation", throwIfNotFound: true);
        m_UI_SkipDialog = m_UI.FindAction("SkipDialog", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // OnFoot
    private readonly InputActionMap m_OnFoot;
    private IOnFootActions m_OnFootActionsCallbackInterface;
    private readonly InputAction m_OnFoot_Movement;
    private readonly InputAction m_OnFoot_Jump;
    private readonly InputAction m_OnFoot_Look;
    private readonly InputAction m_OnFoot_Crouch;
    private readonly InputAction m_OnFoot_Sprint;
    private readonly InputAction m_OnFoot_Interact;
    private readonly InputAction m_OnFoot_SwitchTools;
    private readonly InputAction m_OnFoot_SwitchActionMaps;
    private readonly InputAction m_OnFoot_OperateTool;
    private readonly InputAction m_OnFoot_Reload;
    private readonly InputAction m_OnFoot_Astrolabe;
    private readonly InputAction m_OnFoot_Flashlight;
    private readonly InputAction m_OnFoot_Flaregun;
    private readonly InputAction m_OnFoot_LightningBottle;
    private readonly InputAction m_OnFoot_EastButton;
    private readonly InputAction m_OnFoot_SouthButton;
    public struct OnFootActions
    {
        private @PlayerInput m_Wrapper;
        public OnFootActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_OnFoot_Movement;
        public InputAction @Jump => m_Wrapper.m_OnFoot_Jump;
        public InputAction @Look => m_Wrapper.m_OnFoot_Look;
        public InputAction @Crouch => m_Wrapper.m_OnFoot_Crouch;
        public InputAction @Sprint => m_Wrapper.m_OnFoot_Sprint;
        public InputAction @Interact => m_Wrapper.m_OnFoot_Interact;
        public InputAction @SwitchTools => m_Wrapper.m_OnFoot_SwitchTools;
        public InputAction @SwitchActionMaps => m_Wrapper.m_OnFoot_SwitchActionMaps;
        public InputAction @OperateTool => m_Wrapper.m_OnFoot_OperateTool;
        public InputAction @Reload => m_Wrapper.m_OnFoot_Reload;
        public InputAction @Astrolabe => m_Wrapper.m_OnFoot_Astrolabe;
        public InputAction @Flashlight => m_Wrapper.m_OnFoot_Flashlight;
        public InputAction @Flaregun => m_Wrapper.m_OnFoot_Flaregun;
        public InputAction @LightningBottle => m_Wrapper.m_OnFoot_LightningBottle;
        public InputAction @EastButton => m_Wrapper.m_OnFoot_EastButton;
        public InputAction @SouthButton => m_Wrapper.m_OnFoot_SouthButton;
        public InputActionMap Get() { return m_Wrapper.m_OnFoot; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OnFootActions set) { return set.Get(); }
        public void SetCallbacks(IOnFootActions instance)
        {
            if (m_Wrapper.m_OnFootActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnMovement;
                @Jump.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnJump;
                @Look.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnLook;
                @Crouch.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnCrouch;
                @Crouch.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnCrouch;
                @Crouch.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnCrouch;
                @Sprint.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSprint;
                @Sprint.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSprint;
                @Sprint.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSprint;
                @Interact.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnInteract;
                @SwitchTools.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSwitchTools;
                @SwitchTools.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSwitchTools;
                @SwitchTools.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSwitchTools;
                @SwitchActionMaps.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSwitchActionMaps;
                @SwitchActionMaps.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSwitchActionMaps;
                @SwitchActionMaps.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSwitchActionMaps;
                @OperateTool.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnOperateTool;
                @OperateTool.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnOperateTool;
                @OperateTool.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnOperateTool;
                @Reload.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnReload;
                @Reload.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnReload;
                @Reload.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnReload;
                @Astrolabe.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnAstrolabe;
                @Astrolabe.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnAstrolabe;
                @Astrolabe.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnAstrolabe;
                @Flashlight.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnFlashlight;
                @Flashlight.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnFlashlight;
                @Flashlight.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnFlashlight;
                @Flaregun.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnFlaregun;
                @Flaregun.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnFlaregun;
                @Flaregun.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnFlaregun;
                @LightningBottle.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnLightningBottle;
                @LightningBottle.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnLightningBottle;
                @LightningBottle.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnLightningBottle;
                @EastButton.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEastButton;
                @EastButton.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEastButton;
                @EastButton.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEastButton;
                @SouthButton.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSouthButton;
                @SouthButton.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSouthButton;
                @SouthButton.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSouthButton;
            }
            m_Wrapper.m_OnFootActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Crouch.started += instance.OnCrouch;
                @Crouch.performed += instance.OnCrouch;
                @Crouch.canceled += instance.OnCrouch;
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @SwitchTools.started += instance.OnSwitchTools;
                @SwitchTools.performed += instance.OnSwitchTools;
                @SwitchTools.canceled += instance.OnSwitchTools;
                @SwitchActionMaps.started += instance.OnSwitchActionMaps;
                @SwitchActionMaps.performed += instance.OnSwitchActionMaps;
                @SwitchActionMaps.canceled += instance.OnSwitchActionMaps;
                @OperateTool.started += instance.OnOperateTool;
                @OperateTool.performed += instance.OnOperateTool;
                @OperateTool.canceled += instance.OnOperateTool;
                @Reload.started += instance.OnReload;
                @Reload.performed += instance.OnReload;
                @Reload.canceled += instance.OnReload;
                @Astrolabe.started += instance.OnAstrolabe;
                @Astrolabe.performed += instance.OnAstrolabe;
                @Astrolabe.canceled += instance.OnAstrolabe;
                @Flashlight.started += instance.OnFlashlight;
                @Flashlight.performed += instance.OnFlashlight;
                @Flashlight.canceled += instance.OnFlashlight;
                @Flaregun.started += instance.OnFlaregun;
                @Flaregun.performed += instance.OnFlaregun;
                @Flaregun.canceled += instance.OnFlaregun;
                @LightningBottle.started += instance.OnLightningBottle;
                @LightningBottle.performed += instance.OnLightningBottle;
                @LightningBottle.canceled += instance.OnLightningBottle;
                @EastButton.started += instance.OnEastButton;
                @EastButton.performed += instance.OnEastButton;
                @EastButton.canceled += instance.OnEastButton;
                @SouthButton.started += instance.OnSouthButton;
                @SouthButton.performed += instance.OnSouthButton;
                @SouthButton.canceled += instance.OnSouthButton;
            }
        }
    }
    public OnFootActions @OnFoot => new OnFootActions(this);

    // Sailing
    private readonly InputActionMap m_Sailing;
    private ISailingActions m_SailingActionsCallbackInterface;
    private readonly InputAction m_Sailing_Look;
    private readonly InputAction m_Sailing_BoatYawDirection;
    private readonly InputAction m_Sailing_ToPlayerControls;
    private readonly InputAction m_Sailing_IncreaseSail;
    private readonly InputAction m_Sailing_DecreaseSail;
    private readonly InputAction m_Sailing_BoomRotateRight;
    private readonly InputAction m_Sailing_BoomRotateLeft;
    private readonly InputAction m_Sailing_FireAreaFlare;
    private readonly InputAction m_Sailing_PauseMenu;
    private readonly InputAction m_Sailing_JournalMenu;
    private readonly InputAction m_Sailing_ThirdToFirst;
    private readonly InputAction m_Sailing_EastButton;
    private readonly InputAction m_Sailing_SouthButton;
    public struct SailingActions
    {
        private @PlayerInput m_Wrapper;
        public SailingActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Look => m_Wrapper.m_Sailing_Look;
        public InputAction @BoatYawDirection => m_Wrapper.m_Sailing_BoatYawDirection;
        public InputAction @ToPlayerControls => m_Wrapper.m_Sailing_ToPlayerControls;
        public InputAction @IncreaseSail => m_Wrapper.m_Sailing_IncreaseSail;
        public InputAction @DecreaseSail => m_Wrapper.m_Sailing_DecreaseSail;
        public InputAction @BoomRotateRight => m_Wrapper.m_Sailing_BoomRotateRight;
        public InputAction @BoomRotateLeft => m_Wrapper.m_Sailing_BoomRotateLeft;
        public InputAction @FireAreaFlare => m_Wrapper.m_Sailing_FireAreaFlare;
        public InputAction @PauseMenu => m_Wrapper.m_Sailing_PauseMenu;
        public InputAction @JournalMenu => m_Wrapper.m_Sailing_JournalMenu;
        public InputAction @ThirdToFirst => m_Wrapper.m_Sailing_ThirdToFirst;
        public InputAction @EastButton => m_Wrapper.m_Sailing_EastButton;
        public InputAction @SouthButton => m_Wrapper.m_Sailing_SouthButton;
        public InputActionMap Get() { return m_Wrapper.m_Sailing; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SailingActions set) { return set.Get(); }
        public void SetCallbacks(ISailingActions instance)
        {
            if (m_Wrapper.m_SailingActionsCallbackInterface != null)
            {
                @Look.started -= m_Wrapper.m_SailingActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_SailingActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_SailingActionsCallbackInterface.OnLook;
                @BoatYawDirection.started -= m_Wrapper.m_SailingActionsCallbackInterface.OnBoatYawDirection;
                @BoatYawDirection.performed -= m_Wrapper.m_SailingActionsCallbackInterface.OnBoatYawDirection;
                @BoatYawDirection.canceled -= m_Wrapper.m_SailingActionsCallbackInterface.OnBoatYawDirection;
                @ToPlayerControls.started -= m_Wrapper.m_SailingActionsCallbackInterface.OnToPlayerControls;
                @ToPlayerControls.performed -= m_Wrapper.m_SailingActionsCallbackInterface.OnToPlayerControls;
                @ToPlayerControls.canceled -= m_Wrapper.m_SailingActionsCallbackInterface.OnToPlayerControls;
                @IncreaseSail.started -= m_Wrapper.m_SailingActionsCallbackInterface.OnIncreaseSail;
                @IncreaseSail.performed -= m_Wrapper.m_SailingActionsCallbackInterface.OnIncreaseSail;
                @IncreaseSail.canceled -= m_Wrapper.m_SailingActionsCallbackInterface.OnIncreaseSail;
                @DecreaseSail.started -= m_Wrapper.m_SailingActionsCallbackInterface.OnDecreaseSail;
                @DecreaseSail.performed -= m_Wrapper.m_SailingActionsCallbackInterface.OnDecreaseSail;
                @DecreaseSail.canceled -= m_Wrapper.m_SailingActionsCallbackInterface.OnDecreaseSail;
                @BoomRotateRight.started -= m_Wrapper.m_SailingActionsCallbackInterface.OnBoomRotateRight;
                @BoomRotateRight.performed -= m_Wrapper.m_SailingActionsCallbackInterface.OnBoomRotateRight;
                @BoomRotateRight.canceled -= m_Wrapper.m_SailingActionsCallbackInterface.OnBoomRotateRight;
                @BoomRotateLeft.started -= m_Wrapper.m_SailingActionsCallbackInterface.OnBoomRotateLeft;
                @BoomRotateLeft.performed -= m_Wrapper.m_SailingActionsCallbackInterface.OnBoomRotateLeft;
                @BoomRotateLeft.canceled -= m_Wrapper.m_SailingActionsCallbackInterface.OnBoomRotateLeft;
                @FireAreaFlare.started -= m_Wrapper.m_SailingActionsCallbackInterface.OnFireAreaFlare;
                @FireAreaFlare.performed -= m_Wrapper.m_SailingActionsCallbackInterface.OnFireAreaFlare;
                @FireAreaFlare.canceled -= m_Wrapper.m_SailingActionsCallbackInterface.OnFireAreaFlare;
                @PauseMenu.started -= m_Wrapper.m_SailingActionsCallbackInterface.OnPauseMenu;
                @PauseMenu.performed -= m_Wrapper.m_SailingActionsCallbackInterface.OnPauseMenu;
                @PauseMenu.canceled -= m_Wrapper.m_SailingActionsCallbackInterface.OnPauseMenu;
                @JournalMenu.started -= m_Wrapper.m_SailingActionsCallbackInterface.OnJournalMenu;
                @JournalMenu.performed -= m_Wrapper.m_SailingActionsCallbackInterface.OnJournalMenu;
                @JournalMenu.canceled -= m_Wrapper.m_SailingActionsCallbackInterface.OnJournalMenu;
                @ThirdToFirst.started -= m_Wrapper.m_SailingActionsCallbackInterface.OnThirdToFirst;
                @ThirdToFirst.performed -= m_Wrapper.m_SailingActionsCallbackInterface.OnThirdToFirst;
                @ThirdToFirst.canceled -= m_Wrapper.m_SailingActionsCallbackInterface.OnThirdToFirst;
                @EastButton.started -= m_Wrapper.m_SailingActionsCallbackInterface.OnEastButton;
                @EastButton.performed -= m_Wrapper.m_SailingActionsCallbackInterface.OnEastButton;
                @EastButton.canceled -= m_Wrapper.m_SailingActionsCallbackInterface.OnEastButton;
                @SouthButton.started -= m_Wrapper.m_SailingActionsCallbackInterface.OnSouthButton;
                @SouthButton.performed -= m_Wrapper.m_SailingActionsCallbackInterface.OnSouthButton;
                @SouthButton.canceled -= m_Wrapper.m_SailingActionsCallbackInterface.OnSouthButton;
            }
            m_Wrapper.m_SailingActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @BoatYawDirection.started += instance.OnBoatYawDirection;
                @BoatYawDirection.performed += instance.OnBoatYawDirection;
                @BoatYawDirection.canceled += instance.OnBoatYawDirection;
                @ToPlayerControls.started += instance.OnToPlayerControls;
                @ToPlayerControls.performed += instance.OnToPlayerControls;
                @ToPlayerControls.canceled += instance.OnToPlayerControls;
                @IncreaseSail.started += instance.OnIncreaseSail;
                @IncreaseSail.performed += instance.OnIncreaseSail;
                @IncreaseSail.canceled += instance.OnIncreaseSail;
                @DecreaseSail.started += instance.OnDecreaseSail;
                @DecreaseSail.performed += instance.OnDecreaseSail;
                @DecreaseSail.canceled += instance.OnDecreaseSail;
                @BoomRotateRight.started += instance.OnBoomRotateRight;
                @BoomRotateRight.performed += instance.OnBoomRotateRight;
                @BoomRotateRight.canceled += instance.OnBoomRotateRight;
                @BoomRotateLeft.started += instance.OnBoomRotateLeft;
                @BoomRotateLeft.performed += instance.OnBoomRotateLeft;
                @BoomRotateLeft.canceled += instance.OnBoomRotateLeft;
                @FireAreaFlare.started += instance.OnFireAreaFlare;
                @FireAreaFlare.performed += instance.OnFireAreaFlare;
                @FireAreaFlare.canceled += instance.OnFireAreaFlare;
                @PauseMenu.started += instance.OnPauseMenu;
                @PauseMenu.performed += instance.OnPauseMenu;
                @PauseMenu.canceled += instance.OnPauseMenu;
                @JournalMenu.started += instance.OnJournalMenu;
                @JournalMenu.performed += instance.OnJournalMenu;
                @JournalMenu.canceled += instance.OnJournalMenu;
                @ThirdToFirst.started += instance.OnThirdToFirst;
                @ThirdToFirst.performed += instance.OnThirdToFirst;
                @ThirdToFirst.canceled += instance.OnThirdToFirst;
                @EastButton.started += instance.OnEastButton;
                @EastButton.performed += instance.OnEastButton;
                @EastButton.canceled += instance.OnEastButton;
                @SouthButton.started += instance.OnSouthButton;
                @SouthButton.performed += instance.OnSouthButton;
                @SouthButton.canceled += instance.OnSouthButton;
            }
        }
    }
    public SailingActions @Sailing => new SailingActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_Navigate;
    private readonly InputAction m_UI_Submit;
    private readonly InputAction m_UI_Cancel;
    private readonly InputAction m_UI_Point;
    private readonly InputAction m_UI_Click;
    private readonly InputAction m_UI_ScrollWheel;
    private readonly InputAction m_UI_MiddleClick;
    private readonly InputAction m_UI_RightClick;
    private readonly InputAction m_UI_TrackedDevicePosition;
    private readonly InputAction m_UI_TrackedDeviceOrientation;
    private readonly InputAction m_UI_SkipDialog;
    public struct UIActions
    {
        private @PlayerInput m_Wrapper;
        public UIActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Navigate => m_Wrapper.m_UI_Navigate;
        public InputAction @Submit => m_Wrapper.m_UI_Submit;
        public InputAction @Cancel => m_Wrapper.m_UI_Cancel;
        public InputAction @Point => m_Wrapper.m_UI_Point;
        public InputAction @Click => m_Wrapper.m_UI_Click;
        public InputAction @ScrollWheel => m_Wrapper.m_UI_ScrollWheel;
        public InputAction @MiddleClick => m_Wrapper.m_UI_MiddleClick;
        public InputAction @RightClick => m_Wrapper.m_UI_RightClick;
        public InputAction @TrackedDevicePosition => m_Wrapper.m_UI_TrackedDevicePosition;
        public InputAction @TrackedDeviceOrientation => m_Wrapper.m_UI_TrackedDeviceOrientation;
        public InputAction @SkipDialog => m_Wrapper.m_UI_SkipDialog;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @Navigate.started -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                @Navigate.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                @Navigate.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                @Submit.started -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                @Submit.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                @Submit.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                @Cancel.started -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                @Cancel.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                @Cancel.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                @Point.started -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Point.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Point.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Click.started -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                @ScrollWheel.started -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                @MiddleClick.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                @MiddleClick.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                @MiddleClick.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                @RightClick.started -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                @RightClick.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                @RightClick.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                @TrackedDevicePosition.started -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDevicePosition;
                @TrackedDevicePosition.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDevicePosition;
                @TrackedDevicePosition.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDevicePosition;
                @TrackedDeviceOrientation.started -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDeviceOrientation;
                @SkipDialog.started -= m_Wrapper.m_UIActionsCallbackInterface.OnSkipDialog;
                @SkipDialog.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnSkipDialog;
                @SkipDialog.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnSkipDialog;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Navigate.started += instance.OnNavigate;
                @Navigate.performed += instance.OnNavigate;
                @Navigate.canceled += instance.OnNavigate;
                @Submit.started += instance.OnSubmit;
                @Submit.performed += instance.OnSubmit;
                @Submit.canceled += instance.OnSubmit;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
                @Point.started += instance.OnPoint;
                @Point.performed += instance.OnPoint;
                @Point.canceled += instance.OnPoint;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
                @ScrollWheel.started += instance.OnScrollWheel;
                @ScrollWheel.performed += instance.OnScrollWheel;
                @ScrollWheel.canceled += instance.OnScrollWheel;
                @MiddleClick.started += instance.OnMiddleClick;
                @MiddleClick.performed += instance.OnMiddleClick;
                @MiddleClick.canceled += instance.OnMiddleClick;
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
                @TrackedDevicePosition.started += instance.OnTrackedDevicePosition;
                @TrackedDevicePosition.performed += instance.OnTrackedDevicePosition;
                @TrackedDevicePosition.canceled += instance.OnTrackedDevicePosition;
                @TrackedDeviceOrientation.started += instance.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.performed += instance.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.canceled += instance.OnTrackedDeviceOrientation;
                @SkipDialog.started += instance.OnSkipDialog;
                @SkipDialog.performed += instance.OnSkipDialog;
                @SkipDialog.canceled += instance.OnSkipDialog;
            }
        }
    }
    public UIActions @UI => new UIActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IOnFootActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnSwitchTools(InputAction.CallbackContext context);
        void OnSwitchActionMaps(InputAction.CallbackContext context);
        void OnOperateTool(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnAstrolabe(InputAction.CallbackContext context);
        void OnFlashlight(InputAction.CallbackContext context);
        void OnFlaregun(InputAction.CallbackContext context);
        void OnLightningBottle(InputAction.CallbackContext context);
        void OnEastButton(InputAction.CallbackContext context);
        void OnSouthButton(InputAction.CallbackContext context);
    }
    public interface ISailingActions
    {
        void OnLook(InputAction.CallbackContext context);
        void OnBoatYawDirection(InputAction.CallbackContext context);
        void OnToPlayerControls(InputAction.CallbackContext context);
        void OnIncreaseSail(InputAction.CallbackContext context);
        void OnDecreaseSail(InputAction.CallbackContext context);
        void OnBoomRotateRight(InputAction.CallbackContext context);
        void OnBoomRotateLeft(InputAction.CallbackContext context);
        void OnFireAreaFlare(InputAction.CallbackContext context);
        void OnPauseMenu(InputAction.CallbackContext context);
        void OnJournalMenu(InputAction.CallbackContext context);
        void OnThirdToFirst(InputAction.CallbackContext context);
        void OnEastButton(InputAction.CallbackContext context);
        void OnSouthButton(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnNavigate(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnPoint(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnScrollWheel(InputAction.CallbackContext context);
        void OnMiddleClick(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
        void OnTrackedDevicePosition(InputAction.CallbackContext context);
        void OnTrackedDeviceOrientation(InputAction.CallbackContext context);
        void OnSkipDialog(InputAction.CallbackContext context);
    }
}
